include $(CLEAR_VARS)

FAAD_SOURCE := $(XMMS_PLUGINS)/faad

LOCAL_SRC_FILES := $(FAAD_SOURCE)/faad.c

LOCAL_C_INCLUDES := $(LOCAL_PATH) $(FAAD_INCLUDE) $(GLIB_INCLUDES) $(XMMS_INCLUDES)
LOCAL_CFLAGS := $(DEBUG_FLAG)
LOCAL_MODULE := faad
LOCAL_LDLIBS := -llog
LOCAL_SHARED_LIBRARIES := glib-2.0 xmms2
LOCAL_STATIC_LIBRARIES := faadlib

include $(BUILD_SHARED_LIBRARY)
