include $(CLEAR_VARS)

FLAC_SOURCE := $(XMMS_PLUGINS)/flac

LOCAL_SRC_FILES := \
	$(FLAC_SOURCE)/flac.c

LOCAL_C_INCLUDES := $(FLAC_INCLUDE) $(GLIB_INCLUDES) $(XMMS_INCLUDES)
LOCAL_CFLAGS := -fPIC $(DEBUG_FLAG)

LOCAL_SHARED_LIBRARIES := glib-2.0 xmms2
LOCAL_STATIC_LIBRARIES := flaclib
LOCAL_MODULE := flac
LOCAL_LDLIBS := -llog

include $(BUILD_SHARED_LIBRARY)
