include $(CLEAR_VARS)

ID3V2_SOURCE := $(XMMS_PLUGINS)/id3v2

LOCAL_SRC_FILES := \
	$(ID3V2_SOURCE)/id3.c \
	$(ID3V2_SOURCE)/id3v2plugin.c

LOCAL_C_INCLUDES := $(ID3V2_SOURCE) $(GLIB_INCLUDES) $(XMMS_INCLUDES)
LOCAL_CFLAGS := -fPIC $(DEBUG_FLAG)

LOCAL_SHARED_LIBRARIES := glib-2.0 xmms2
LOCAL_MODULE := id3v2
LOCAL_LDLIBS := -llog

include $(BUILD_SHARED_LIBRARY)
