include $(CLEAR_VARS)

MODPLUG_SOURCE := $(XMMS_PLUGINS)/modplug

LOCAL_SRC_FILES := $(MODPLUG_SOURCE)/modplug.c

LOCAL_C_INCLUDES := $(MODPLUG_INCLUDE) $(GLIB_INCLUDES) $(XMMS_INCLUDES)
LOCAL_MODULE := modplug
LOCAL_LDLIBS := -llog
LOCAL_SHARED_LIBRARIES := glib-2.0 xmms2
LOCAL_STATIC_LIBRARIES := modpluglib

include $(BUILD_SHARED_LIBRARY)
