include $(CLEAR_VARS)

MUSEPACK_SOURCE := $(XMMS_PLUGINS)/musepack

LOCAL_SRC_FILES := \
	$(MUSEPACK_SOURCE)/musepack.c

LOCAL_C_INCLUDES := $(MUSEPACK_INCLUDES) $(GLIB_INCLUDES) $(XMMS_INCLUDES)

LOCAL_SHARED_LIBRARIES := glib-2.0 xmms2
LOCAL_STATIC_LIBRARIES := musepacklib
LOCAL_MODULE := musepack
LOCAL_LDLIBS := -llog

include $(BUILD_SHARED_LIBRARY)
