include $(CLEAR_VARS)

NULL_SOURCE := $(XMMS_PLUGINS)/null

LOCAL_SRC_FILES := \
	$(NULL_SOURCE)/null.c

LOCAL_C_INCLUDES := $(GLIB_INCLUDES) $(XMMS_INCLUDES)
LOCAL_CFLAGS := -fPIC $(DEBUG_FLAG)

LOCAL_SHARED_LIBRARIES := glib-2.0 xmms2
LOCAL_MODULE := null

include $(BUILD_SHARED_LIBRARY)
