include $(CLEAR_VARS)

OPUS_SOURCE := $(XMMS_PLUGINS)/opus

LOCAL_SRC_FILES := \
	$(OPUS_SOURCE)/opus.c

LOCAL_C_INCLUDES := $(OPUS_INCLUDES) $(OPUSFILE_INCLUDES) $(OGG_INCLUDE) $(GLIB_INCLUDES) $(XMMS_INCLUDES)
LOCAL_CFLAGS := -fPIC $(DEBUG_FLAG)

LOCAL_SHARED_LIBRARIES := glib-2.0 xmms2
LOCAL_STATIC_LIBRARIES := opusfilelib opuslib ogglib
LOCAL_MODULE := opus
LOCAL_LDLIBS := -llog

include $(BUILD_SHARED_LIBRARY)
