include $(CLEAR_VARS)

REPLAYGAIN_SOURCE := $(XMMS_PLUGINS)/replaygain

LOCAL_SRC_FILES := $(REPLAYGAIN_SOURCE)/replaygain.c

LOCAL_C_INCLUDES := $(GLIB_INCLUDES) $(XMMS_INCLUDES)
LOCAL_CFLAGS := -fPIC $(DEBUG_FLAGS)

LOCAL_SHARED_LIBRARIES := glib-2.0 xmms2
LOCAL_MODULE := replaygain
LOCAL_LDLIBS := -llog

include $(BUILD_SHARED_LIBRARY)
