include $(CLEAR_VARS)

SNDFILE_SOURCE := $(XMMS_PLUGINS)/sndfile

LOCAL_SRC_FILES := \
	$(SNDFILE_SOURCE)/sndfile.c

LOCAL_C_INCLUDES := $(SNDFILE_INCLUDES) $(GLIB_INCLUDES) $(XMMS_INCLUDES)
LOCAL_CFLAGS := -fPIC $(DEBUG_FLAG)

LOCAL_SHARED_LIBRARIES := glib-2.0 xmms2
LOCAL_STATIC_LIBRARIES := sndfilelib
LOCAL_MODULE := sndfile
LOCAL_LDLIBS := -llog

include $(BUILD_SHARED_LIBRARY)
