include $(CLEAR_VARS)

TREMOR_SOURCE := $(XMMS_PLUGINS)/tremor

LOCAL_SRC_FILES := $(TREMOR_SOURCE)/tremor.c

LOCAL_C_INCLUDES := $(LOCAL_PATH) $(OGG_INCLUDE) $(GLIB_INCLUDES) $(XMMS_INCLUDES)
LOCAL_CFLAGS := $(DEBUG_FLAG)
LOCAL_MODULE := tremor
LOCAL_LDLIBS := -llog
LOCAL_SHARED_LIBRARIES := glib-2.0 xmms2
LOCAL_STATIC_LIBRARIES := tremorlib ogglib

include $(BUILD_SHARED_LIBRARY)
