include $(CLEAR_VARS)

OPUS_CONFIG := $(LOCAL_PATH)/config/opus

LOCAL_SRC_FILES := \
	$(OPUS_SOURCE)/celt/bands.c \
	$(OPUS_SOURCE)/celt/celt.c \
	$(OPUS_SOURCE)/celt/celt_encoder.c \
	$(OPUS_SOURCE)/celt/celt_decoder.c \
	$(OPUS_SOURCE)/celt/cwrs.c \
	$(OPUS_SOURCE)/celt/entcode.c \
	$(OPUS_SOURCE)/celt/entdec.c \
	$(OPUS_SOURCE)/celt/entenc.c \
	$(OPUS_SOURCE)/celt/kiss_fft.c \
	$(OPUS_SOURCE)/celt/laplace.c \
	$(OPUS_SOURCE)/celt/mathops.c \
	$(OPUS_SOURCE)/celt/mdct.c \
	$(OPUS_SOURCE)/celt/modes.c \
	$(OPUS_SOURCE)/celt/pitch.c \
	$(OPUS_SOURCE)/celt/celt_lpc.c \
	$(OPUS_SOURCE)/celt/quant_bands.c \
	$(OPUS_SOURCE)/celt/rate.c \
	$(OPUS_SOURCE)/celt/vq.c \
	$(OPUS_SOURCE)/silk/CNG.c \
	$(OPUS_SOURCE)/silk/code_signs.c \
	$(OPUS_SOURCE)/silk/init_decoder.c \
	$(OPUS_SOURCE)/silk/decode_core.c \
	$(OPUS_SOURCE)/silk/decode_frame.c \
	$(OPUS_SOURCE)/silk/decode_parameters.c \
	$(OPUS_SOURCE)/silk/decode_indices.c \
	$(OPUS_SOURCE)/silk/decode_pulses.c \
	$(OPUS_SOURCE)/silk/decoder_set_fs.c \
	$(OPUS_SOURCE)/silk/dec_API.c \
	$(OPUS_SOURCE)/silk/enc_API.c \
	$(OPUS_SOURCE)/silk/encode_indices.c \
	$(OPUS_SOURCE)/silk/encode_pulses.c \
	$(OPUS_SOURCE)/silk/gain_quant.c \
	$(OPUS_SOURCE)/silk/interpolate.c \
	$(OPUS_SOURCE)/silk/LP_variable_cutoff.c \
	$(OPUS_SOURCE)/silk/NLSF_decode.c \
	$(OPUS_SOURCE)/silk/NSQ.c \
	$(OPUS_SOURCE)/silk/NSQ_del_dec.c \
	$(OPUS_SOURCE)/silk/PLC.c \
	$(OPUS_SOURCE)/silk/shell_coder.c \
	$(OPUS_SOURCE)/silk/tables_gain.c \
	$(OPUS_SOURCE)/silk/tables_LTP.c \
	$(OPUS_SOURCE)/silk/tables_NLSF_CB_NB_MB.c \
	$(OPUS_SOURCE)/silk/tables_NLSF_CB_WB.c \
	$(OPUS_SOURCE)/silk/tables_other.c \
	$(OPUS_SOURCE)/silk/tables_pitch_lag.c \
	$(OPUS_SOURCE)/silk/tables_pulses_per_block.c \
	$(OPUS_SOURCE)/silk/VAD.c \
	$(OPUS_SOURCE)/silk/control_audio_bandwidth.c \
	$(OPUS_SOURCE)/silk/quant_LTP_gains.c \
	$(OPUS_SOURCE)/silk/VQ_WMat_EC.c \
	$(OPUS_SOURCE)/silk/HP_variable_cutoff.c \
	$(OPUS_SOURCE)/silk/NLSF_encode.c \
	$(OPUS_SOURCE)/silk/NLSF_VQ.c \
	$(OPUS_SOURCE)/silk/NLSF_unpack.c \
	$(OPUS_SOURCE)/silk/NLSF_del_dec_quant.c \
	$(OPUS_SOURCE)/silk/process_NLSFs.c \
	$(OPUS_SOURCE)/silk/stereo_LR_to_MS.c \
	$(OPUS_SOURCE)/silk/stereo_MS_to_LR.c \
	$(OPUS_SOURCE)/silk/check_control_input.c \
	$(OPUS_SOURCE)/silk/control_SNR.c \
	$(OPUS_SOURCE)/silk/init_encoder.c \
	$(OPUS_SOURCE)/silk/control_codec.c \
	$(OPUS_SOURCE)/silk/A2NLSF.c \
	$(OPUS_SOURCE)/silk/ana_filt_bank_1.c \
	$(OPUS_SOURCE)/silk/biquad_alt.c \
	$(OPUS_SOURCE)/silk/bwexpander_32.c \
	$(OPUS_SOURCE)/silk/bwexpander.c \
	$(OPUS_SOURCE)/silk/debug.c \
	$(OPUS_SOURCE)/silk/decode_pitch.c \
	$(OPUS_SOURCE)/silk/inner_prod_aligned.c \
	$(OPUS_SOURCE)/silk/lin2log.c \
	$(OPUS_SOURCE)/silk/log2lin.c \
	$(OPUS_SOURCE)/silk/LPC_analysis_filter.c \
	$(OPUS_SOURCE)/silk/LPC_inv_pred_gain.c \
	$(OPUS_SOURCE)/silk/table_LSF_cos.c \
	$(OPUS_SOURCE)/silk/NLSF2A.c \
	$(OPUS_SOURCE)/silk/NLSF_stabilize.c \
	$(OPUS_SOURCE)/silk/NLSF_VQ_weights_laroia.c \
	$(OPUS_SOURCE)/silk/pitch_est_tables.c \
	$(OPUS_SOURCE)/silk/resampler.c \
	$(OPUS_SOURCE)/silk/resampler_down2_3.c \
	$(OPUS_SOURCE)/silk/resampler_down2.c \
	$(OPUS_SOURCE)/silk/resampler_private_AR2.c \
	$(OPUS_SOURCE)/silk/resampler_private_down_FIR.c \
	$(OPUS_SOURCE)/silk/resampler_private_IIR_FIR.c \
	$(OPUS_SOURCE)/silk/resampler_private_up2_HQ.c \
	$(OPUS_SOURCE)/silk/resampler_rom.c \
	$(OPUS_SOURCE)/silk/sigm_Q15.c \
	$(OPUS_SOURCE)/silk/sort.c \
	$(OPUS_SOURCE)/silk/sum_sqr_shift.c \
	$(OPUS_SOURCE)/silk/stereo_decode_pred.c \
	$(OPUS_SOURCE)/silk/stereo_encode_pred.c \
	$(OPUS_SOURCE)/silk/stereo_find_predictor.c \
	$(OPUS_SOURCE)/silk/stereo_quant_pred.c \
	$(OPUS_SOURCE)/silk/fixed/LTP_analysis_filter_FIX.c \
	$(OPUS_SOURCE)/silk/fixed/LTP_scale_ctrl_FIX.c \
	$(OPUS_SOURCE)/silk/fixed/corrMatrix_FIX.c \
	$(OPUS_SOURCE)/silk/fixed/encode_frame_FIX.c \
	$(OPUS_SOURCE)/silk/fixed/find_LPC_FIX.c \
	$(OPUS_SOURCE)/silk/fixed/find_LTP_FIX.c \
	$(OPUS_SOURCE)/silk/fixed/find_pitch_lags_FIX.c \
	$(OPUS_SOURCE)/silk/fixed/find_pred_coefs_FIX.c \
	$(OPUS_SOURCE)/silk/fixed/noise_shape_analysis_FIX.c \
	$(OPUS_SOURCE)/silk/fixed/prefilter_FIX.c \
	$(OPUS_SOURCE)/silk/fixed/process_gains_FIX.c \
	$(OPUS_SOURCE)/silk/fixed/regularize_correlations_FIX.c \
	$(OPUS_SOURCE)/silk/fixed/residual_energy16_FIX.c \
	$(OPUS_SOURCE)/silk/fixed/residual_energy_FIX.c \
	$(OPUS_SOURCE)/silk/fixed/solve_LS_FIX.c \
	$(OPUS_SOURCE)/silk/fixed/warped_autocorrelation_FIX.c \
	$(OPUS_SOURCE)/silk/fixed/apply_sine_window_FIX.c \
	$(OPUS_SOURCE)/silk/fixed/autocorr_FIX.c \
	$(OPUS_SOURCE)/silk/fixed/burg_modified_FIX.c \
	$(OPUS_SOURCE)/silk/fixed/k2a_FIX.c \
	$(OPUS_SOURCE)/silk/fixed/k2a_Q16_FIX.c \
	$(OPUS_SOURCE)/silk/fixed/pitch_analysis_core_FIX.c \
	$(OPUS_SOURCE)/silk/fixed/vector_ops_FIX.c \
	$(OPUS_SOURCE)/silk/fixed/schur64_FIX.c \
	$(OPUS_SOURCE)/silk/fixed/schur_FIX.c \
	$(OPUS_SOURCE)/src/opus.c \
	$(OPUS_SOURCE)/src/opus_decoder.c \
	$(OPUS_SOURCE)/src/opus_encoder.c \
	$(OPUS_SOURCE)/src/opus_multistream.c \
	$(OPUS_SOURCE)/src/opus_multistream_encoder.c \
	$(OPUS_SOURCE)/src/opus_multistream_decoder.c \
	$(OPUS_SOURCE)/src/repacketizer.c \
	$(OPUS_SOURCE)/src/analysis.c \
	$(OPUS_SOURCE)/src/mlp.c \
	$(OPUS_SOURCE)/src/mlp_data.c

LOCAL_CFLAGS := -std=gnu99 -DHAVE_CONFIG_H -fPIC -fvisibility=hidden
LOCAL_C_INCLUDES := $(OPUS_CONFIG) $(OPUS_INCLUDES) $(LOCAL_PATH)/$(OPUS_SOURCE)/celt $(LOCAL_PATH)/$(OPUS_SOURCE)/silk $(LOCAL_PATH)/$(OPUS_SOURCE)/silk/fixed

LOCAL_MODULE := opuslib

include $(BUILD_STATIC_LIBRARY)
