include $(CLEAR_VARS)

LOCAL_SRC_FILES := \
	$(OPUSFILE_SOURCE)/http.c \
	$(OPUSFILE_SOURCE)/info.c \
	$(OPUSFILE_SOURCE)/internal.c \
	$(OPUSFILE_SOURCE)/stream.c \
	$(OPUSFILE_SOURCE)/opusfile.c \
	$(OPUSFILE_SOURCE)/wincerts.c

LOCAL_CFLAGS := -fPIC
LOCAL_C_INCLUDES := $(LOCAL_PATH)/$(OPUSFILE_SOURCE) $(OPUSFILE_INCLUDES) $(OGG_INCLUDE) $(OPUS_INCLUDES)

LOCAL_STATIC_LIBRARIES := ogglib

LOCAL_MODULE := opusfilelib

include $(BUILD_STATIC_LIBRARY)
